version: 0.2
phases:
 install:
   runtime-versions:
     docker: 20
 pre_build:
   commands:
     - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
     - REPOSITORY_URI=300560903441.dkr.ecr.us-east-1.amazonaws.com/nodejs-test
     - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
     - IMAGE_TAG=latest
 build:
   commands:
     - docker build -t nodejs-test .
     - docker tag nodejs-test:latest 300560903441.dkr.ecr.us-east-1.amazonaws.com/nodejs-test:latest
 post_build:
   commands:
     - docker push 300560903441.dkr.ecr.us-east-1.amazonaws.com/nodejs-test:latest
     - docker tag nodejs-test:latest 300560903441.dkr.ecr.us-east-1.amazonaws.com/nodejs-test:latest
     - printf '[{"name":"nodejs-test","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
 files: imagedefinitions.json
